baseURL = 'https://sayakatolik.com/'
languageCode = 'id-ID'
title = 'Saya Katolik'
theme = 'ananke'
defaultContentLanguage = "id"

[params]
custom_css = ["custom.css"]
site_logo = "/images/logo-sm.png"
favicon = "/images/logo-sm.png"

[pagination]
pagerSize = 10

[languages.id]
contentDir = "content/id"
languageCode = 'id-ID'
weight = 1
[languages.id.menus]
  [[languages.id.menus.main]]
    name = 'Beranda'
    pageRef = '/'
    weight = 10