baseURL = 'https://sayakatolik.com/'
languageCode = 'id-ID'
title = 'Saya Katolik'
theme = 'ananke'

[params]
custom_css = ["custom.css"]
site_logo = "/images/logo-sm.png"
favicon = "/images/logo-sm.png"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10